title: Warranty Now Void
email: wnv@warrantynowvoid.com
description: It's a website. With poop jokes and stuff. Read it. Or don't. I'm not your dad.
locale: en_US
baseurl: ""
url: "https://warrantynowvoid.com"

permalink: /:categories/:year/:month/:day/
twitter_username: warrantynowvoid
github_username:  warrantynowvoid

markdown: kramdown
plugins:
  # - jekyll-feed

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - .vendor/
  - tools/
