title: Warranty Now Void
email: wnv@warrantynowvoid.com
description: It's a website. With poop jokes and stuff. Read it. Or don't. I'm not your dad.
locale: en_US
baseurl: ""
url: "https://warrantynowvoid.com"

permalink: /:categories/:year/:month/:day/
twitter_username: warrantynowvoid
github_username:  warrantynowvoid

lsi: true

markdown: kramdown
safe: false

# turn this off to disable vibrantjs on each post page
# for faster builds
vibrant-posts: false

# turn this off to disable auto thumbnail generation on build
# or if you just don't want to install ImageMagick
generate-thumbnails:
  enabled: true
  height: 600
  width: 1200
  path: "assets/img/lol/thumbs/"

pagination:
  enabled: true
  per_page: 10
  sort_reverse: true
  trail:
    before: 2
    after: 2

autopages:
  enabled: true
  collections:
    enabled: false
  categories:
    layouts:
      - 'autopage_category.html'
    title: ':cat Posts - Warranty Now Void'
    permalink: '/:cat/'
  tags:
    layouts:
      - 'autopage_tags.html'
    title: ':tag Posts - Warranty Now Void'
    permalink: '/tag/:tag'
    slugify:
      mode: 'ascii'
      cased: false

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - .vendor/
  - tools/
