version: 0.1
frontend:
  phases:
    preBuild:
      commands:
        - yum install -y gcc ImageMagick-devel make which
        - npm install node-vibrant
        - gem install bundler
        - bundle install --with production
    build:
      commands:
        - bundle exec jekyll b
  artifacts:
    baseDirectory: _site
    files:
      - '**/*'
  cache:
    paths: []
  customHeaders:
    - pattern: '**/*'
      headers:
        - key: 'Content-Security-Policy'
          value: "default-src https: 'unsafe-inline'; object-src 'none'"
      headers:
        - key: 'Strict-Transport-Security'
          value: 'max-age=63072000; includeSubDomains; preload'
      headers:
        - key: 'Referrer-Policy'
          value: 'same-origin, strict-origin-when-cross-origin'
      headers:
        - key: 'X-Content-Type-Options'
          value: 'nosniff'
      headers:
        - key: 'X-Frame-Options'
          value: 'DENY'
      headers:
        - key: 'X-XSS-Protection'
          value: '1; mode=block'
    - pattern: '/assets/img/**'
      headers:
        - key: 'Cache-Control'
          value: 'public, max-age=31536000'
    - pattern: '/assets/mp3/**'
      headers:
        - key: 'Cache-Control'
          value: 'public, max-age=31536000'