version: 0.1
frontend:
  phases:
    preBuild:
      commands:
        - yum install -y gcc ImageMagick-devel make which
        - npm install node-vibrant
        - gem install bundler
        - bundle install --with production
    build:
      commands:
        - bundle exec jekyll b
  artifacts:
    baseDirectory: _site
    files:
      - '**/*'
  cache:
    paths: []
  customHeaders:
    - pattern: '**/*'
      headers:
        - key: 'Content-Security-Policy'
          value: "default-src 'self'; img-src https: https://i.imgur.com; script-src https: https://s.imgur.com https://platform.twitter.com https://osto.us https://platform.twitter.com https://code.jquery.com https://use.fontawesome.com https://cdnjs.cloudflare.com https://stackpath.bootstrapcdn.com; font-src https: https://fonts.googleapis.com; style-src https: https://use.fontawesome.com https://fonts.googleapis.com https://stackpath.bootstrapcdn.com nonce-EDNnf03nceIOfn39fn3e8h4sdfc; frame-src https: https://art19.com https://www.youtube.com https://imgur.com/; object-src 'none'"
        - key: 'Strict-Transport-Security'
          value: 'max-age=63072000; includeSubDomains; preload'
        - key: 'Referrer-Policy'
          value: 'same-origin, strict-origin-when-cross-origin'
        - key: 'X-Content-Type-Options'
          value: 'nosniff'
        - key: 'X-Frame-Options'
          value: 'DENY'
        - key: 'X-XSS-Protection'
          value: '1; mode=block'
    - pattern: '/assets/img/**'
      headers:
        - key: 'Cache-Control'
          value: 'public, max-age=31536000'
    - pattern: '/assets/mp3/**'
      headers:
        - key: 'Cache-Control'
          value: 'public, max-age=31536000'